from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any, List
import json

try:
    from fpdf import FPDF
except ImportError as e:
    raise ImportError("fpdf is required for PDF generation. Please install with `pip install fpdf`.") from e


def generate_pdf(
    predicted_crop: str,
    predicted_yield: float,
    weather_data: Dict[str, Any],
    chart_path: Optional[str] = None,
    output_dir: str = "outputs/reports",
    filename_prefix: str = "Crop_Report"
) -> str:
    """
    Create a clean, sectioned PDF report summarizing:
    - Smart Farming Report (Header)
    - Date, City
    - Recommended Crop & Predicted Yield
    - Weather Summary (Temp, Rainfall, Humidity)
    - Embedded Chart Image
    - Notes/Remarks section

    Saves under outputs/reports/ with timestamp (YYYY-MM-DD_HH-MM).
    Returns absolute file path.
    """
    reports_dir = Path(output_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now().strftime("%Y-%m-%d_%H-%M")
    crop_suffix = f"_{str(predicted_crop).strip().lower()}" if predicted_crop else ""
    pdf_path = reports_dir / f"{filename_prefix}{crop_suffix}_{ts}.pdf"

    city = str(weather_data.get("city", "Unknown")) if isinstance(weather_data, dict) else "Unknown"
    temp = float(weather_data.get("temperature", 0.0)) if isinstance(weather_data, dict) else 0.0
    rain = float(weather_data.get("rainfall", 0.0)) if isinstance(weather_data, dict) else 0.0
    hum = float(weather_data.get("humidity", 0.0)) if isinstance(weather_data, dict) else 0.0

    pdf = FPDF(orientation='P', unit='mm', format='A4')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    TITLE_COLOR = (27, 94, 32)
    HEADER_FILL = (235, 255, 235)
    TEXT_COLOR = (0, 0, 0)

    # Header
    pdf.set_fill_color(*HEADER_FILL)
    pdf.rect(x=10, y=10, w=190, h=14, style='F')
    pdf.set_xy(10, 10)
    pdf.set_text_color(*TITLE_COLOR)
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(190, 10, "Smart Farming Report", ln=True, align='C')

    pdf.ln(4)
    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 8, f"City: {city}", ln=True)

    # Recommendation
    pdf.ln(2)
    pdf.set_text_color(*TITLE_COLOR)
    pdf.set_font('Arial', 'B', 13)
    pdf.cell(0, 8, "[Crop] Recommendation", ln=True)

    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font('Arial', '', 12)
    left_w, right_w = 60, 120
    pdf.cell(left_w, 8, "Recommended Crop:", border=0)
    pdf.cell(right_w, 8, f"{predicted_crop}", ln=True, border=0)
    pdf.cell(left_w, 8, "Predicted Yield:", border=0)
    pdf.cell(right_w, 8, f"{float(predicted_yield):.2f} tons/hectare", ln=True, border=0)

    # Weather
    pdf.ln(2)
    pdf.set_text_color(*TITLE_COLOR)
    pdf.set_font('Arial', 'B', 13)
    pdf.cell(0, 8, "[Weather] Summary", ln=True)

    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font('Arial', '', 12)
    pdf.cell(left_w, 8, "Temperature:", border=0)
    pdf.cell(right_w, 8, f"{temp:.2f} °C", ln=True, border=0)
    pdf.cell(left_w, 8, "Rainfall:", border=0)
    pdf.cell(right_w, 8, f"{rain:.2f} mm", ln=True, border=0)
    pdf.cell(left_w, 8, "Humidity:", border=0)
    pdf.cell(right_w, 8, f"{hum:.2f} %", ln=True, border=0)

    # Chart
    pdf.ln(2)
    pdf.set_text_color(*TITLE_COLOR)
    pdf.set_font('Arial', 'B', 13)
    pdf.cell(0, 8, "[Chart] Yield vs Weather", ln=True)

    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font('Arial', '', 12)
    if chart_path and Path(chart_path).exists():
        pdf.image(chart_path, x=15, y=None, w=180)
        pdf.ln(4)
    else:
        pdf.cell(0, 8, "Chart not available.", ln=True)

    # Notes
    pdf.ln(2)
    pdf.set_text_color(*TITLE_COLOR)
    pdf.set_font('Arial', 'B', 13)
    pdf.cell(0, 8, "[Notes] Remarks", ln=True)

    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 6, "This report provides an AI-assisted recommendation based on current weather inputs. "
                        "Please consider local agronomic practices, soil tests, and expert advice before sowing.")

    # Footer
    pdf.ln(4)
    pdf.set_font('Arial', 'I', 10)
    pdf.cell(0, 8, "Generated by Smart Farming ML System", ln=True, align='C')

    pdf.output(str(pdf_path))
    return str(pdf_path.resolve())


def generate_batch_reports(
    crops_data: List[Dict[str, Any]],
    charts_dir: str = "outputs/charts",
    reports_dir: str = "outputs/reports",
    summary_path: str = "outputs/reports/report_summary.json"
) -> Dict[str, Any]:
    """
    Batch-generate charts and PDF reports for multiple crops and store metadata.

    crops_data: list of dicts, each with keys like:
      - crop (str, required)
      - df (pd.DataFrame with columns: yield, temperature, rainfall) OR
        temperature, rainfall, yield arrays to build df
      - weather (dict with keys: city, temperature, rainfall, humidity)
      - predicted_yield (float)

    Returns: dict containing 'items' (list of per-crop metadata) and 'summary_path'.
    Also writes JSON summary to summary_path for dashboard/API consumption.
    """
    from scripts.visuals.chart_generator import generate_yield_chart  # local import to avoid cycles
    import pandas as pd  # for type checks when building df

    results: List[Dict[str, Any]] = []

    Path(reports_dir).mkdir(parents=True, exist_ok=True)
    Path(charts_dir).mkdir(parents=True, exist_ok=True)

    for entry in crops_data:
        crop = str(entry.get("crop", "")).strip()
        if not crop:
            # Skip invalid entries
            continue

        # Build DataFrame for chart
        df = entry.get("df")
        if df is None:
            temp = entry.get("temperature")
            rain = entry.get("rainfall")
            yld = entry.get("yield")
            if temp is not None and rain is not None and yld is not None:
                df = pd.DataFrame({
                    "temperature": temp,
                    "rainfall": rain,
                    "yield": yld,
                })

        chart_path = None
        if df is not None:
            chart_path = generate_yield_chart(df, output_dir=charts_dir, crop_name=crop)

        pdf_path = generate_pdf(
            predicted_crop=crop,
            predicted_yield=float(entry.get("predicted_yield", 0.0)),
            weather_data=entry.get("weather", {}),
            chart_path=chart_path,
            output_dir=reports_dir,
        )

        results.append({
            "crop": crop,
            "chart_path": chart_path,
            "pdf_path": pdf_path,
        })

    # Save JSON summary
    summary_file = Path(summary_path)
    summary_file.parent.mkdir(parents=True, exist_ok=True)
    with summary_file.open("w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    return {"items": results, "summary_path": str(summary_file.resolve())}


